BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "info" (
	"key"	TEXT,
	"value"	TEXT
);
CREATE TABLE IF NOT EXISTS "skills" (
	"chapter"	TEXT,
	"section"	TEXT
);
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL UNIQUE,
	"pwd"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
